spring.application.name=Chapter-7-Spring-Boot
spring.datasource.url=jdbc:mysql://localhost:3306/Springboot
spring.datasource.username=root
spring.datasource.password=Yash123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true